### PR TITLE
macos build, .app file added to /app folder

### PR DESCRIPTION
**Pull request by batuhand**
.app file added for issue #191

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
Hello,
Thank you very much for your contribution.
The butterfly.app directory seems very big. Is it possible to add the directory in the .gitignore?

**Comment by CodeDoctorDE** [comment]
If you remove it please use `git commit --amend` and `git push -f` that the repo won't be so big

**Comment by CodeDoctorDE** [comment]
Usuallly executable files are built using github on every commit. When we add the executable to the git project, it won't be up to date. If the macos project works, I can add it to the build workflow and it can be included in the next release

**Comment by batuhand** [comment]
> Usuallly executable files are built using github on every commit. When we add the executable to the git project, it won't be up to date. If the macos project works, I can add it to the build workflow and it can be included in the next release

It's working as expected I suppose. Adding the directory into gitignore

**Comment by CodeDoctorDE** [comment]
Hi, thank you. Now you need to delete the directory and commit them

**Comment by batuhand** [comment]
> Hi, thank you. Now you need to delete the directory and commit them

done @CodeDoctorDE

**Comment by CodeDoctorDE** [comment]
image
you need to delete it from the file system add use `git add .` and `git commit -m "Remove app directory"` and `git push`

**Comment by CodeDoctorDE** [comment]
Nice.
Does everything work when you try to run the application using `flutter run -d macos` and does everything work (exporting images, importing images)?

**Comment by batuhand** [comment]
I didn't see any errors, I can check again and open an issue if I see an error

**Comment by CodeDoctorDE** [comment]
Did you use `flutter run -d macos`?

I found out that macos/Runner/AppDelegate.swift needs to be changed:
```patch
import Cocoa
import FlutterMacOS

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
  override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
-    return true
+    return false
  }
}
```

If you need help or get errors, feel free to reply. I want to be sure everything works before merging it. I don't have a mac to test it

**Comment by batuhand** [comment]
> Did you use `flutter run -d macos`?

Yes, app runs smoothly without any change required, I just didn't test every single feature but it runs.

**Comment by CodeDoctorDE** [comment]
> > Did you use `flutter run -d macos`?
> 
> Yes, app runs smoothly without any change required, I just didn't test every single feature but it runs.

Okay nice. If you do `flutter build macos`, can you  give me the output directory and which files needs to be included?

**Comment by batuhand** [comment]
.app file will be created at /build/macos/Build/Products/Release/your_app.app after running `flutter build macos`

**Comment by CodeDoctorDE** [comment]
Nice, please look if everything works, apply the patch above and I can merge it

**Review by batuhand — COMMENTED** [review]
applying

**Comment by batuhand** [comment]
@CodeDoctorDE Where is the .patch file exactly?

**Comment by CodeDoctorDE** [comment]
https://github.com/LinwoodCloud/Butterfly/blob/develop/app/macos/Runner/AppDelegate.swift#L7 this needs to be changed

**Pull request merged**
