### PR TITLE
Publish to WinGet GitHub Action

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
Hello @CodeDoctorDE, 

I have created this PR to add GitHub Action to your repository. But before merging it, you'll have to do some things:

1. Create a Personal Access Token (PAT) with `public_repo` scope and add it to repository as a secret `WINGET_TOKEN` (if you choose to keep some other name of the secret, please update the PR as well)
2. You will have to re-publish v1.2.1 to trigger the action (just to test the configuration is correct and all things in the action are working properly)

### CODE REVIEW

**Review by CodeDoctorDE — APPROVED** [review]
Thank you!

**Comment by vedantmgoyal2009** [comment]
@CodeDoctorDE you will have to publish a stable release. Currently, the action does not support pre-release since winget currently does not support release channels and hence I haven't added support to the action to. Once winget will support release channels, I will update the action to support them accordingly.

**Comment by CodeDoctorDE** [comment]
Okay, no problem. Normally users should use the stable. I republish it as stable and make it to a pre release after that

**Comment by CodeDoctorDE** [comment]
I released a stable, but the action does not run... i hate ci :/

**Pull request merged**
